apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-ms
  template:
    metadata:
      labels:
        app: cart-ms
    spec:
      containers:
        - name: cart-ms-container
          image: ghcr.io/bmonish/k8-nginx-lb-cart:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cart-ms
spec:
  type: NodePort
  selector:
    app: cart-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30100
